export interface TherapistListing {
  id: string;
  slug: string;
  name: string;
  title: string;
  specialty: string;
  address: string;
  city: string;
  state: string;
  zip: string;
  phone: string;
  website?: string;
  rating?: number;
  reviews?: number;
  accepting_new: boolean;
  telehealth: boolean;
  insurance?: string[];
}

export const mockListings: TherapistListing[] = [
  {
    id: "1",
    slug: "sarah-johnson-lcsw",
    name: "Sarah Johnson",
    title: "LCSW, Certified Christian Counselor",
    specialty: "Anxiety, Depression, Trauma",
    address: "123 Main St",
    city: "Austin",
    state: "TX",
    zip: "78701",
    phone: "(512) 555-0101",
    website: "https://example.com",
    rating: 4.9,
    reviews: 127,
    accepting_new: true,
    telehealth: true,
    insurance: ["Aetna", "BlueCross", "Cigna"],
  },
  {
    id: "2",
    slug: "michael-reyes-lmft",
    name: "Michael Reyes",
    title: "LMFT, Biblical Counseling Specialist",
    specialty: "Marriage & Family, Addiction Recovery",
    address: "456 Oak Ave",
    city: "Denver",
    state: "CO",
    zip: "80202",
    phone: "(303) 555-0202",
    rating: 4.8,
    reviews: 89,
    accepting_new: true,
    telehealth: true,
    insurance: ["United", "Aetna"],
  },
  {
    id: "3",
    slug: "emily-watson-lpc",
    name: "Emily Watson",
    title: "LPC, Christian Trauma Therapist",
    specialty: "PTSD, Childhood Trauma, Anxiety",
    address: "789 Pine Rd",
    city: "Phoenix",
    state: "AZ",
    zip: "85001",
    phone: "(602) 555-0303",
    website: "https://example.com",
    rating: 4.7,
    reviews: 64,
    accepting_new: false,
    telehealth: true,
    insurance: ["BlueCross", "Cigna", "Humana"],
  },
  {
    id: "4",
    slug: "david-chen-psyd",
    name: "David Chen",
    title: "PsyD, Faith-Based Psychologist",
    specialty: "Depression, Life Transitions, Grief",
    address: "321 Elm St",
    city: "Seattle",
    state: "WA",
    zip: "98101",
    phone: "(206) 555-0404",
    rating: 4.9,
    reviews: 203,
    accepting_new: true,
    telehealth: false,
    insurance: ["Kaiser", "Aetna", "United"],
  },
  {
    id: "5",
    slug: "lisa-thompson-lmhc",
    name: "Lisa Thompson",
    title: "LMHC, Christian Counselor",
    specialty: "Anxiety, Stress, Relationship Issues",
    address: "654 Cedar Ln",
    city: "Orlando",
    state: "FL",
    zip: "32801",
    phone: "(407) 555-0505",
    website: "https://example.com",
    rating: 4.6,
    reviews: 45,
    accepting_new: true,
    telehealth: true,
    insurance: ["Cigna", "BlueCross"],
  },
  {
    id: "6",
    slug: "james-mitchell-lcsw",
    name: "James Mitchell",
    title: "LCSW, Addiction Specialist",
    specialty: "Substance Abuse, Co-occurring Disorders",
    address: "987 Birch Blvd",
    city: "Chicago",
    state: "IL",
    zip: "60601",
    phone: "(312) 555-0606",
    rating: 4.8,
    reviews: 156,
    accepting_new: true,
    telehealth: true,
    insurance: ["BlueCross", "Aetna", "United"],
  },
  {
    id: "7",
    slug: "amanda-davis-lpc",
    name: "Amanda Davis",
    title: "LPC, Marriage & Family Therapist",
    specialty: "Couples Therapy, Communication, Faith",
    address: "147 Maple Dr",
    city: "Nashville",
    state: "TN",
    zip: "37201",
    phone: "(615) 555-0707",
    website: "https://example.com",
    rating: 4.9,
    reviews: 178,
    accepting_new: false,
    telehealth: true,
    insurance: ["Aetna", "Cigna", "Humana"],
  },
  {
    id: "8",
    slug: "robert-kim-phd",
    name: "Robert Kim",
    title: "PhD, Christian Psychologist",
    specialty: "Adolescent Therapy, Family Conflict",
    address: "258 Walnut St",
    city: "Atlanta",
    state: "GA",
    zip: "30301",
    phone: "(404) 555-0808",
    rating: 4.7,
    reviews: 92,
    accepting_new: true,
    telehealth: false,
    insurance: ["United", "Kaiser"],
  },
  {
    id: "9",
    slug: "jennifer-lee-lmft",
    name: "Jennifer Lee",
    title: "LMFT, Anxiety & Depression Specialist",
    specialty: "OCD, Panic Disorder, Christian Integration",
    address: "369 Spruce Ave",
    city: "San Diego",
    state: "CA",
    zip: "92101",
    phone: "(619) 555-0909",
    website: "https://example.com",
    rating: 4.8,
    reviews: 134,
    accepting_new: true,
    telehealth: true,
    insurance: ["BlueCross", "Aetna", "Cigna"],
  },
  {
    id: "10",
    slug: "mark-anderson-lcsw",
    name: "Mark Anderson",
    title: "LCSW, Grief & Loss Counselor",
    specialty: "Bereavement, Life Review, Spiritual Integration",
    address: "741 Ash Way",
    city: "Portland",
    state: "OR",
    zip: "97201",
    phone: "(503) 555-1010",
    rating: 4.9,
    reviews: 211,
    accepting_new: true,
    telehealth: true,
    insurance: ["Kaiser", "United", "Aetna"],
  },
];

export const US_STATES = [
  "AL","AK","AZ","AR","CA","CO","CT","DE","FL","GA",
  "HI","ID","IL","IN","IA","KS","KY","LA","ME","MD",
  "MA","MI","MN","MS","MO","MT","NE","NV","NH","NJ",
  "NM","NY","NC","ND","OH","OK","OR","PA","RI","SC",
  "SD","TN","TX","UT","VT","VA","WA","WV","WI","WY"
];

export const SPECIALTIES = [
  "Anxiety", "Depression", "Trauma", "PTSD", "Marriage & Family",
  "Addiction Recovery", "Grief & Loss", "Couples Therapy", "OCD",
  "Panic Disorder", "Adolescent Therapy", "Life Transitions"
];
